import { Link } from "react-router-dom";

import { buildLoginPath, buildSampleDashboardPath, DEMO_EMPTY_PROJECT_ID } from "../constants.js";

export function HomeRoute() {
  return (
    <section className="home-grid">
      <article className="card">
        <h1>__PROJECT_NAME__</h1>
        <p>
          This app was generated by <strong>create-agentic-sql-app</strong> with PostgreSQL session
          authentication and authoritative row-level security. Stored procedures enforce permissions,
          transitions, and validation. The API stays thin. React renders contract data.
        </p>
        <p>
          <Link className="button" to={buildLoginPath(buildSampleDashboardPath())}>
            Sign in to open the sample dashboard
          </Link>
        </p>
      </article>

      <article className="card">
        <h2>What to click in the demo</h2>
        <ol className="command-list">
          <li>
            Sign in as <strong>admin@example.com</strong> with password <code>password123</code>.
          </li>
          <li>
            Open the sample dashboard for project <strong>Agentic SQL Demo</strong>.
          </li>
          <li>
            Review the seeded release <strong>Initial contract-driven release</strong> and approve it.
          </li>
          <li>
            Sign out, sign in as <strong>viewer@example.com</strong>, and try a transition to see a
            permission error.
          </li>
          <li>
            Use <strong>Try invalid transition</strong> as owner to trigger a documented business-rule
            error.
          </li>
          <li>
            Open the{" "}
            <Link to={buildSampleDashboardPath(DEMO_EMPTY_PROJECT_ID)}>empty project dashboard</Link>{" "}
            to see the empty state.
          </li>
        </ol>
      </article>

      <article className="card">
        <h2>Quick local commands</h2>
        <ul className="command-list">
          <li>
            <code>npm run db:up</code> then <code>npm run db:migrate</code> and{" "}
            <code>npm run db:seed</code>
          </li>
          <li>
            <code>npm run dev</code> to run API and web together
          </li>
          <li>
            <code>npm run test</code> to run database, server, and web tests
          </li>
        </ul>
      </article>
    </section>
  );
}
