import { Link } from "react-router-dom";

import {
  buildLoginPath,
  buildReleaseRiskDashboardPath,
  DEMO_EMPTY_SERVICE_ID,
} from "../constants.js";

export function HomeRoute() {
  return (
    <section className="home-grid">
      <article className="card">
        <h1>__PROJECT_NAME__</h1>
        <p>
          This release-risk app was generated by <strong>create-agentic-sql-app</strong> with
          PostgreSQL session authentication and authoritative row-level security.
        </p>
        <p>
          <Link className="button" to={buildLoginPath(buildReleaseRiskDashboardPath())}>
            Sign in to open the release risk dashboard
          </Link>
        </p>
      </article>

      <article className="card">
        <h2>What to click in the demo</h2>
        <ol className="command-list">
          <li>
            Sign in as <strong>admin@example.com</strong> with password <code>password123</code>.
          </li>
          <li>
            Open the release risk dashboard for service <strong>Checkout API</strong>.
          </li>
          <li>
            Review the computed risk score for <strong>Checkout reliability release</strong>.
          </li>
          <li>
            Sign out, sign in as <strong>viewer@example.com</strong>, and try a transition to see a
            permission error.
          </li>
          <li>
            Open the{" "}
            <Link to={buildReleaseRiskDashboardPath(DEMO_EMPTY_SERVICE_ID)}>
              empty service dashboard
            </Link>{" "}
            to see the empty state.
          </li>
        </ol>
      </article>
    </section>
  );
}
