import { Link } from "react-router-dom";

import {
  buildReleaseRiskDashboardPath,
  DEMO_EMPTY_SERVICE_ID,
  DEMO_SERVICE_ID,
  DEMO_VIEWER_USER_ID,
} from "../constants.js";

export function HomeRoute() {
  return (
    <section className="home-grid">
      <article className="card">
        <h1>__PROJECT_NAME__</h1>
        <p>
          This app was generated by <strong>create-agentic-sql-app</strong> to demonstrate a
          PostgreSQL-first release-risk domain. Stored procedures compute risk, enforce transitions,
          and validate permissions. The API stays thin. React renders contract data and tests verify
          behavior at the owning layer.
        </p>
        <p>
          <Link className="button" to={buildReleaseRiskDashboardPath()}>
            Open release risk dashboard
          </Link>
        </p>
      </article>

      <article className="card">
        <h2>What to click in the demo</h2>
        <ol className="command-list">
          <li>
            Open the release risk dashboard for service <strong>Checkout API</strong>.
          </li>
          <li>
            Review PostgreSQL-computed risk for <strong>Checkout reliability release</strong> and
            approve it.
          </li>
          <li>
            Switch to{" "}
            <Link to={buildReleaseRiskDashboardPath(DEMO_SERVICE_ID, DEMO_VIEWER_USER_ID)}>
              viewer context
            </Link>{" "}
            and try a transition to see a permission error.
          </li>
          <li>
            Use <strong>Try invalid transition (demo)</strong> as owner to trigger a documented
            business-rule error.
          </li>
          <li>
            Open the{" "}
            <Link to={buildReleaseRiskDashboardPath(DEMO_EMPTY_SERVICE_ID)}>
              empty service dashboard
            </Link>{" "}
            to see the empty state.
          </li>
        </ol>
      </article>

      <article className="card">
        <h2>Quick local commands</h2>
        <ul className="command-list">
          <li>
            <code>npm run db:up</code> then <code>npm run db:migrate</code> and{" "}
            <code>npm run db:seed</code>
          </li>
          <li>
            <code>npm run dev</code> to run API and web together
          </li>
          <li>
            <code>npm run test</code> to run database, server, and web tests
          </li>
        </ul>
      </article>

      <article className="card">
        <h2>Generated docs to review</h2>
        <ul className="doc-list">
          <li>
            <code>AGENTS.md</code> architecture boundaries for agents
          </li>
          <li>
            <code>TASKS.md</code> implementation sequence
          </li>
          <li>
            <code>DB_API_CONTRACT.md</code> route and procedure contracts
          </li>
          <li>
            <code>ERROR_CODES.md</code> error payload expectations
          </li>
          <li>
            <code>SCENARIOS.md</code> expected user flows
          </li>
          <li>
            <code>TESTING_STRATEGY.md</code> required test commands
          </li>
          <li>
            <code>docs/screenshots/README.md</code> screenshot capture guidance
          </li>
        </ul>
      </article>
    </section>
  );
}
